async function generateDailySummary() {
    const resultDiv = document.getElementById('dailyResult');
    resultDiv.style.display = 'block';
    resultDiv.textContent = 'Generating daily summary...';
    try {
        const result = await fetch(`${API_URL}/reports/daily`, { method: 'POST' });
        const json = await result.json();
        const r = json.report;
        const byStatus = Object.entries(r.by_status || {}).map(([k, v]) =>
            `<tr><td>${k}</td><td>${v}</td></tr>`).join('');
        resultDiv.innerHTML = `
            <p><strong>Report ID:</strong> ${json.report_id}</p>
            <p><strong>Date:</strong> ${r.date}</p>
            <p><strong>Total Orders:</strong> ${r.total_orders}</p>
            <table><thead><tr><th>Status</th><th>Count</th></tr></thead><tbody>${byStatus}</tbody></table>`;
    } catch (error) {
        resultDiv.textContent = 'Error: ' + error.message;
    }
}

async function generateWeeklySummary() {
    const resultDiv = document.getElementById('weeklyResult');
    resultDiv.style.display = 'block';
    resultDiv.textContent = 'Generating weekly summary...';
    try {
        const result = await fetch(`${API_URL}/reports/weekly`, { method: 'POST' });
        const json = await result.json();
        const r = json.report;
        const byStatus = Object.entries(r.by_status || {}).map(([k, v]) =>
            `<tr><td>${k}</td><td>${v}</td></tr>`).join('');
        const lowStock = (r.low_stock || []).map(sku => `<li>${sku}</li>`).join('');
        resultDiv.innerHTML = `
            <p><strong>Report ID:</strong> ${json.report_id}</p>
            <p><strong>Week Ending:</strong> ${r.week_ending}</p>
            <p><strong>Total Orders:</strong> ${r.total_orders} &nbsp;|&nbsp; <strong>Total SKUs:</strong> ${r.total_skus}</p>
            <table><thead><tr><th>Status</th><th>Count</th></tr></thead><tbody>${byStatus}</tbody></table>
            <p><strong>Low Stock SKUs:</strong></p><ul>${lowStock || '<li>None</li>'}</ul>`;
    } catch (error) {
        resultDiv.textContent = 'Error: ' + error.message;
    }
}


async function generateReconciliation() {
    const resultDiv = document.getElementById('reconciliationResult');
    resultDiv.style.display = 'block';
    resultDiv.textContent = 'Generating reconciliation report...';

    try {
        const result = await fetch(`${API_URL}/reports/reconciliation`);
        const json = await result.json();
        
        if (json.report && json.report.length > 0) {
            let table = '<table><thead><tr><th>SKU</th><th>Quantity</th><th>Available</th><th>Reserved</th></tr></thead><tbody>';
            json.report.forEach(item => {
                table += `<tr>
                    <td>${item.sku || 'N/A'}</td>
                    <td>${item.quantity || 0}</td>
                    <td>${item.available || 0}</td>
                    <td>${item.reserved || 0}</td>
                </tr>`;
            });
            table += '</tbody></table>';
            resultDiv.innerHTML = `<p>Report ID: ${json.report_id} | Total Items: ${json.total_items}</p>` + table;
        } else {
            resultDiv.textContent = 'No data in report';
        }
    } catch (error) {
        resultDiv.textContent = 'Error: ' + error.message;
    }
}

async function listReports(forceRefresh = false) {
    const resultDiv = document.getElementById('reportsResult');
    resultDiv.style.display = 'block';
    resultDiv.textContent = 'Loading reports...';

    try {
        const url = forceRefresh ? `${API_URL}/reports?refresh=true` : `${API_URL}/reports`;
        const result = await fetch(url);
        const json = await result.json();
        
        if (json.records && json.records.length > 0) {
            let table = '<table><thead><tr><th>Report Type</th><th>Generated By</th><th>Status</th><th>Created</th></tr></thead><tbody>';
            json.records.forEach(record => {
                const fields = record.fields;
                table += `<tr>
                    <td>${fields.report_type || 'N/A'}</td>
                    <td>${fields.generated_by || 'N/A'}</td>
                    <td>${fields.status || 'N/A'}</td>
                    <td>${fields.created_at ? new Date(fields.created_at).toLocaleString() : 'N/A'}</td>
                </tr>`;
            });
            table += '</tbody></table>';
            resultDiv.innerHTML = table;
        } else {
            resultDiv.textContent = 'No reports found';
        }
    } catch (error) {
        resultDiv.textContent = 'Error: ' + error.message;
    }
}

document.addEventListener('DOMContentLoaded', () => {
    if (document.getElementById('reportsResult')) listReports();
});
