async function generateDailySummary() {
    const resultDiv = document.getElementById('dailyResult');
    resultDiv.style.display = 'block';
    resultDiv.textContent = 'Generating daily summary...';
    try {
        const result = await fetch(`${API_URL}/reports/daily`, { method: 'POST' });
        const json = await result.json();
        const r = json.report;
        const byStatus = Object.entries(r.by_status || {}).map(([k, v]) => `<tr><td>${k}</td><td>${v}</td></tr>`).join('');
        const byPriority = Object.entries(r.by_priority || {}).map(([k, v]) => `<tr><td>${k}</td><td>${v}</td></tr>`).join('');
        resultDiv.innerHTML = `<div><strong>Report ID:</strong> ${json.report_id}</div><div><strong>Date:</strong> ${r.date}</div><div><strong>Total Orders:</strong> ${r.total_orders} &nbsp;|&nbsp; <strong>Picklists:</strong> ${r.picklists_generated} &nbsp;|&nbsp; <strong>Exceptions:</strong> ${r.exceptions_raised} &nbsp;|&nbsp; <strong>Backorders:</strong> ${r.backorders_created}</div><div><strong>By Status:</strong></div><table><thead><tr><th>Status</th><th>Count</th></tr></thead><tbody>${byStatus}</tbody></table><div><strong>By Priority:</strong></div><table><thead><tr><th>Priority</th><th>Count</th></tr></thead><tbody>${byPriority}</tbody></table>`;
    } catch (error) {
        resultDiv.textContent = 'Error: ' + error.message;
    }
}

async function generateWeeklySummary() {
    const resultDiv = document.getElementById('weeklyResult');
    resultDiv.style.display = 'block';
    resultDiv.textContent = 'Generating weekly summary...';
    try {
        const result = await fetch(`${API_URL}/reports/weekly`, { method: 'POST' });
        const json = await result.json();
        const r = json.report;
        const byStatus = Object.entries(r.by_status || {}).map(([k, v]) => `<tr><td>${k}</td><td>${v}</td></tr>`).join('');
        const byPriority = Object.entries(r.by_priority || {}).map(([k, v]) => `<tr><td>${k}</td><td>${v}</td></tr>`).join('');
        const lowStock = (r.low_stock || []).map(sku => `<li>${sku}</li>`).join('');
        resultDiv.innerHTML = `<div><strong>Report ID:</strong> ${json.report_id}</div><div><strong>Week Ending:</strong> ${r.week_ending}</div><div><strong>Total Orders:</strong> ${r.total_orders} &nbsp;|&nbsp; <strong>Fulfillment Rate:</strong> ${r.fulfillment_rate}%</div><div><strong>Total SKUs:</strong> ${r.total_skus} &nbsp;|&nbsp; <strong>Goods Receipts:</strong> ${r.goods_receipts} &nbsp;|&nbsp; <strong>Stock Received:</strong> ${r.total_stock_received}</div><div><strong>Exceptions:</strong> ${r.exceptions_raised} &nbsp;|&nbsp; <strong>Backorders:</strong> ${r.backorders_created}</div><div><strong>By Status:</strong></div><table><thead><tr><th>Status</th><th>Count</th></tr></thead><tbody>${byStatus}</tbody></table><div><strong>By Priority:</strong></div><table><thead><tr><th>Priority</th><th>Count</th></tr></thead><tbody>${byPriority}</tbody></table><div><strong>Low Stock SKUs:</strong></div><ul>${lowStock || '<li>None</li>'}</ul>`;
    } catch (error) {
        resultDiv.textContent = 'Error: ' + error.message;
    }
}


async function generateReconciliation() {
    const resultDiv = document.getElementById('reconciliationResult');
    resultDiv.style.display = 'block';
    resultDiv.textContent = 'Generating reconciliation report...';

    try {
        const result = await fetch(`${API_URL}/reports/reconciliation`);
        const json = await result.json();
        
        if (json.report && json.report.length > 0) {
            let table = '<table><thead><tr><th>SKU</th><th>Quantity</th><th>Available</th><th>Reserved</th></tr></thead><tbody>';
            json.report.forEach(item => {
                table += `<tr>
                    <td>${item.sku || 'N/A'}</td>
                    <td>${item.quantity || 0}</td>
                    <td>${item.available || 0}</td>
                    <td>${item.reserved || 0}</td>
                </tr>`;
            });
            table += '</tbody></table>';
            resultDiv.innerHTML = `<div>Report ID: ${json.report_id} | Total Items: ${json.total_items}</div>` + table;
        } else {
            resultDiv.textContent = 'No data in report';
        }
    } catch (error) {
        resultDiv.textContent = 'Error: ' + error.message;
    }
}

async function listReports(forceRefresh = false) {
    const resultDiv = document.getElementById('reportsResult');
    resultDiv.style.display = 'block';
    resultDiv.textContent = 'Loading reports...';

    try {
        const url = forceRefresh ? `${API_URL}/reports?refresh=true` : `${API_URL}/reports`;
        const result = await fetch(url);
        const json = await result.json();
        
        if (json.records && json.records.length > 0) {
            let table = '<table><thead><tr><th>Report Type</th><th>Generated By</th><th>Status</th><th>Created</th><th>Download</th></tr></thead><tbody>';
            json.records.forEach(record => {
                const fields = record.fields;
                const safeData = encodeURIComponent(fields.report_data || '{}');
                table += `<tr>
                    <td>${fields.report_type || 'N/A'}</td>
                    <td>${fields.generated_by || 'N/A'}</td>
                    <td>${fields.status || 'N/A'}</td>
                    <td>${fields.created_at ? new Date(fields.created_at).toLocaleString() : 'N/A'}</td>
                    <td><button class="btn-outline" onclick="downloadReport('${record.id}', '${fields.report_type}', decodeURIComponent('${safeData}'))"><i class="bi bi-download"></i></button></td>
                </tr>`;
            });
            table += '</tbody></table>';
            resultDiv.innerHTML = table;
        } else {
            resultDiv.textContent = 'No reports found';
        }
    } catch (error) {
        resultDiv.textContent = 'Error: ' + error.message;
    }
}

function downloadReport(id, type, dataStr) {
    const d = JSON.parse(dataStr);

    const metricCard = (label, value) =>
        `<div class="card"><div class="label">${label}</div><div class="value">${value}</div></div>`;

    const tableFrom = (obj, col1 = 'Key', col2 = 'Value') =>
        `<table><thead><tr><th>${col1}</th><th>${col2}</th></tr></thead><tbody>${
            Object.entries(obj).map(([k,v]) => `<tr><td>${k}</td><td>${v}</td></tr>`).join('')
        }</tbody></table>`;

    let sections = '';
    if (type === 'Daily Summary') {
        sections = `
            <div class="cards">
                ${metricCard('Date', d.date)}
                ${metricCard('Total Orders', d.total_orders)}
                ${metricCard('Picklists Generated', d.picklists_generated ?? '-')}
                ${metricCard('Exceptions Raised', d.exceptions_raised ?? '-')}
                ${metricCard('Backorders Created', d.backorders_created ?? '-')}
            </div>
            <h3>Orders by Status</h3>${tableFrom(d.by_status || {}, 'Status', 'Count')}
            <h3>Orders by Priority</h3>${tableFrom(d.by_priority || {}, 'Priority', 'Count')}`;
    } else if (type === 'Weekly Summary') {
        const lowStock = (d.low_stock || []).length
            ? `<ul>${d.low_stock.map(s => `<li>${s}</li>`).join('')}</ul>`
            : '<p>None</p>';
        sections = `
            <div class="cards">
                ${metricCard('Week Ending', d.week_ending)}
                ${metricCard('Total Orders', d.total_orders)}
                ${metricCard('Fulfillment Rate', (d.fulfillment_rate ?? '-') + '%')}
                ${metricCard('Total SKUs', d.total_skus)}
                ${metricCard('Goods Receipts', d.goods_receipts ?? '-')}
                ${metricCard('Stock Received', d.total_stock_received ?? '-')}
                ${metricCard('Exceptions Raised', d.exceptions_raised ?? '-')}
                ${metricCard('Backorders Created', d.backorders_created ?? '-')}
            </div>
            <h3>Orders by Status</h3>${tableFrom(d.by_status || {}, 'Status', 'Count')}
            <h3>Orders by Priority</h3>${tableFrom(d.by_priority || {}, 'Priority', 'Count')}
            <h3>Low Stock SKUs</h3>${lowStock}`;
    } else if (type === 'Stock Reconciliation') {
        const headers = ['sku', 'quantity', 'available', 'reserved'];
        sections = `<table><thead><tr>${headers.map(h => `<th>${h}</th>`).join('')}</tr></thead><tbody>${
            (Array.isArray(d) ? d : []).map(row => `<tr>${headers.map(h => `<td>${row[h] ?? '-'}</td>`).join('')}</tr>`).join('')
        }</tbody></table>`;
    } else {
        sections = tableFrom(d);
    }

    const html = `<!DOCTYPE html><html><head><title>${type}</title><style>
        *{box-sizing:border-box;margin:0;padding:0}
        body{font-family:'Segoe UI',sans-serif;padding:40px;font-size:13px;color:#111}
        .header{border-bottom:2px solid #4f46e5;padding-bottom:12px;margin-bottom:24px}
        .header h1{font-size:20px;color:#4f46e5}
        .header p{color:#666;font-size:12px;margin-top:4px}
        .cards{display:flex;flex-wrap:wrap;gap:12px;margin-bottom:24px}
        .card{border:1px solid #e5e7eb;border-radius:6px;padding:12px 16px;min-width:120px}
        .card .label{font-size:11px;color:#6b7280;text-transform:uppercase;letter-spacing:.5px}
        .card .value{font-size:18px;font-weight:700;color:#4f46e5;margin-top:4px}
        h3{font-size:13px;font-weight:600;margin:20px 0 8px;color:#374151}
        table{width:100%;border-collapse:collapse;margin-bottom:16px}
        th{background:#f3f4f6;padding:8px 12px;text-align:left;font-size:11px;text-transform:uppercase;letter-spacing:.5px;border-bottom:1px solid #e5e7eb}
        td{padding:8px 12px;border-bottom:1px solid #f3f4f6}
        ul{padding-left:20px}li{margin:4px 0}
        .footer{margin-top:32px;font-size:11px;color:#9ca3af;border-top:1px solid #e5e7eb;padding-top:12px}
        @media print{body{padding:20px}}
    </style></head><body>
        <div class="header"><h1>${type}</h1><p>Report ID: ${id} &nbsp;|&nbsp; Generated: ${new Date().toLocaleString()}</p></div>
        ${sections}
        <div class="footer">Generated by RPA Warehouse System</div>
    </body></html>`;

    const w = window.open('', '_blank');
    w.document.write(html);
    w.document.close();
    w.focus();
    w.print();
    w.close();
}

document.addEventListener('DOMContentLoaded', () => {
    if (document.getElementById('reportsResult')) listReports();
});
