async function generateReconciliation() {
    const resultDiv = document.getElementById('reconciliationResult');
    resultDiv.style.display = 'block';
    resultDiv.textContent = 'Generating reconciliation report...';

    try {
        const result = await fetch(`${API_URL}/reports/reconciliation`);
        const json = await result.json();
        
        if (json.report && json.report.length > 0) {
            let table = '<table><thead><tr><th>SKU</th><th>Quantity</th><th>Available</th><th>Reserved</th></tr></thead><tbody>';
            json.report.forEach(item => {
                table += `<tr>
                    <td>${item.sku || 'N/A'}</td>
                    <td>${item.quantity || 0}</td>
                    <td>${item.available || 0}</td>
                    <td>${item.reserved || 0}</td>
                </tr>`;
            });
            table += '</tbody></table>';
            resultDiv.innerHTML = `<p>Report ID: ${json.report_id} | Total Items: ${json.total_items}</p>` + table;
        } else {
            resultDiv.textContent = 'No data in report';
        }
    } catch (error) {
        resultDiv.textContent = 'Error: ' + error.message;
    }
}

async function listReports() {
    const resultDiv = document.getElementById('reportsResult');
    resultDiv.style.display = 'block';
    resultDiv.textContent = 'Loading reports...';

    try {
        const result = await fetch(`${API_URL}/reports`);
        const json = await result.json();
        
        if (json.records && json.records.length > 0) {
            let table = '<table><thead><tr><th>Report Type</th><th>Generated By</th><th>Status</th><th>Created</th></tr></thead><tbody>';
            json.records.forEach(record => {
                const fields = record.fields;
                table += `<tr>
                    <td>${fields.report_type || 'N/A'}</td>
                    <td>${fields.generated_by || 'N/A'}</td>
                    <td>${fields.status || 'N/A'}</td>
                    <td>${fields.created_at ? new Date(fields.created_at).toLocaleString() : 'N/A'}</td>
                </tr>`;
            });
            table += '</tbody></table>';
            resultDiv.innerHTML = table;
        } else {
            resultDiv.textContent = 'No reports found';
        }
    } catch (error) {
        resultDiv.textContent = 'Error: ' + error.message;
    }
}
